name: scarica e tieni aggiornati i dati openregio

on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '52 11,19 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
    - name: Installa le utility
      run: |-
        wget https://github.com/johnkerl/miller/releases/download/v5.7.0/mlr.linux.x86_64
        mv mlr.linux.x86_64 mlr
        chmod +x mlr
    - name: scarica i dati json, crea versione CSV e fai il sort
      run: |-
        curl -kL https://openregio.anbsc.it/statistiche/export/5/immobili/0/0/0/json | jq -c 'sort_by(.m_bene)|.[]' >openregio_immobiliDestinati.jsonl
        curl -kL https://openregio.anbsc.it/statistiche/export/1/immobili/0/0/0/json | jq -c 'sort_by(.s_bene)|.[]' >openregio_immobiliGestione.jsonl
        curl -kL https://openregio.anbsc.it/statistiche/export/5/aziende/0/0/0/json | jq -c 'sort_by(.m_bene)|.[]' >openregio_aziendeDestinate.jsonl
        curl -kL https://openregio.anbsc.it/statistiche/export/5/aziende/0/0/0/json | jq -c 'sort_by(.m_bene)|.[]' >openregio_aziendeGestione.jsonl
        curl -kL https://openregio.anbsc.it/statistiche/export_procedure/0/0/0/0/json | jq -c '.[]' >openregio_procedureGestione.jsonl
        ./mlr --j2c unsparsify then clean-whitespace then sort -f m_bene openregio_immobiliDestinati.jsonl >openregio_immobiliDestinati.csv
        ./mlr --j2c unsparsify then clean-whitespace then sort -f s_bene openregio_immobiliGestione.jsonl >openregio_immobiliGestione.csv
        ./mlr --j2c unsparsify then clean-whitespace then sort -f m_bene openregio_aziendeDestinate.jsonl >openregio_aziendeDestinate.csv
        ./mlr --j2c unsparsify then clean-whitespace then sort -f m_bene openregio_aziendeGestione.jsonl >openregio_aziendeGestione.csv
        ./mlr --j2c unsparsify then clean-whitespace then sort -f nome_regione,distretto,ufficio_giudiziario,tipologia_procedura,provvedimento,procedura_rg openregio_procedureGestione.jsonl >openregio_procedureGestione.csv
    - name: crea il TSV del log git
#      run: |-
#        chmod +x ./gitlog.sh
#        ./gitlog.sh
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Data e ora aggiornamento: ${timestamp}" || exit 0
        git push
