name: scarica e tieni aggiornati i dati openregio

on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '52 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
    - name: Installa le utility e assegna path
      run: |-
        pwd
        mkdir -p ~/bin
        cd ~/bin
        wget https://github.com/johnkerl/miller/releases/download/v5.7.0/mlr.linux.x86_64
        mv mlr.linux.x86_64 mlr
        chmod +x mlr
        export PATH=$PATH:~/bin
        cd ~/runner/work/firstaction/firstaction
        mlr --tsv head testEnv.tsv
    - name: scarica i dati json, crea versione CSV e fai il sort
      run: |-
        ./download.sh
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Data e ora aggiornamento: ${timestamp}" || exit 0
        git push
