name: scarica e tieni aggiornati i dati openregio

on:
#  push:
  repository_dispatch:
  schedule:
# le ore github sono -2, quindi se inserisco 5, sono le 7 di mattina
    - cron:  '00 5,7,10,13,16 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
    - name: crea cartella utente bin, e copia dentro l'eseguibile di miller
      run: |-
        mkdir -p ~/bin
        cp bin/mlr ~/bin
        cd ~/bin
        chmod +x mlr
    - name: scarica i dati json, crea versione CSV, crea log e se ci sono aggiornamenti avvisami
      env:
        SUPER_SECRET: ${{ secrets.IFTTT }}
      run: |-
        export PATH=$PATH:~/bin
        ./download.sh
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "Data e ora aggiornamento: ${timestamp}" || exit 0
        git push
