name: scarica i dati

on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '52 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Installa le utility
      run: |-
        sudo apt-get update
        sudo apt-get install miller
        sudo apt-get install jq
    - name: scarica i dati
      run: |-
        curl -kL https://github.com/pcm-dpc/COVID-19/raw/master/dati-json/dpc-covid19-ita-province.json >data.json
        mlr --j2c cat data.json >data.csv
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
