name: Fetch latest data

on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '52 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Install utilities
      run: |-
        sudo apt-get update
        sudo apt-get install miller
        sudo apt-get install jq
    - name: Fetch latest data
      run: |-
        curl -kL https://c19downloads.azureedge.net/downloads/data/data_latest.json >data.json
        mlr --j2c cat data.json >data.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
